/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    permissions: Permission;
    roles: Role;
    users: User;
    sites: Site;
    'audit-logs': AuditLog;
    media: Media;
    articles: Article;
    pages: Page;
    'faq-items': FaqItem;
    characters: Character;
    'site-settings': SiteSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('zh-Hans' | 'zh-Hant' | 'en' | 'ja' | 'ko')
    | ('zh-Hans' | 'zh-Hant' | 'en' | 'ja' | 'ko')[];
  globals: {};
  globalsSelect: {};
  locale: 'zh-Hans' | 'zh-Hant' | 'en' | 'ja' | 'ko';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Read-only catalog maintained by seed. Assign via Roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  slug: string;
  label: string;
  resource:
    | 'articles'
    | 'pages'
    | 'faq-items'
    | 'characters'
    | 'media'
    | 'site-settings'
    | 'sites'
    | 'users'
    | 'roles'
    | 'audit-logs';
  action: 'read' | 'create' | 'update' | 'delete' | 'publish' | 'manage';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * Stable identifier (e.g. editor, site-admin)
   */
  slug: string;
  name: string;
  description?: string | null;
  /**
   * Built-in roles from seed; slug cannot change
   */
  isSystem?: boolean | null;
  /**
   * When enabled, site scope is not restricted for this role
   */
  allSites?: boolean | null;
  /**
   * Permission points granted by this role
   */
  permissions: (number | Permission)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * One or more roles defining permissions for this user
   */
  roles: (number | Role)[];
  /**
   * Required when no assigned role has All Sites. Ignored for allSites roles.
   */
  sites?: (number | Site)[] | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  /**
   * Stable key for CONTENT_SITE_SLUG (e.g. lingxia)
   */
  slug: string;
  name: string;
  /**
   * Canonical site URL without trailing slash
   */
  primaryDomain: string;
  defaultLocale: 'zh-Hans' | 'zh-Hant' | 'en' | 'ja' | 'ko';
  enabledLocales: ('zh-Hans' | 'zh-Hant' | 'en' | 'ja' | 'ko')[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user: number | User;
  action: 'create' | 'update' | 'delete' | 'publish';
  collection: string;
  docId: number;
  slug?: string | null;
  site?: (number | null) | Site;
  at: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  site: number | Site;
  author?: (number | null) | User;
  title: string;
  /**
   * Strategy A: one slug for all locales (e.g. welcome-to-lingxia). Do not change per language.
   */
  slug: string;
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover?: (number | null) | Media;
  tags?: string[] | null;
  status: 'draft' | 'published';
  publishedAt: string;
  /**
   * Locales with complete translations. Web sitemap only includes listed locales.
   */
  localesPublished?: ('zh-Hans' | 'zh-Hant' | 'en' | 'ja' | 'ko')[] | null;
  seo?: {
    /**
     * Overrides page title for search engines when set
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  firstPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site: number | Site;
  title: string;
  /**
   * Strategy A: stable slug (about, privacy). Not localized.
   */
  slug: string;
  layout: 'default' | 'legal' | 'landing' | 'campaign';
  body?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richParagraph';
          }
        | {
            image: number | Media;
            alt: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            text: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            label: string;
            url: string;
            style?: ('primary' | 'secondary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  hero?: {
    headline: string;
    tagline: string;
  };
  heroSocial?: {
    dividerText: string;
  };
  chapterOne?: {
    /**
     * Show chapter eyebrow label on site (e.g. Chapter 01)
     */
    showEyebrow?: boolean | null;
    /**
     * Show chapter main title on site
     */
    showTitle?: boolean | null;
    /**
     * Show pillar title text below each column image
     */
    showPillarTitle?: boolean | null;
    /**
     * Show pillar body text below each column image
     */
    showPillarBody?: boolean | null;
    eyebrow: string;
    title: string;
    pillars: {
      title: string;
      body: string;
      /**
       * Column image (portrait or square recommended)
       */
      image?: (number | null) | Media;
      id?: string | null;
    }[];
  };
  chapterTwo?: {
    /**
     * Show chapter eyebrow label on site (e.g. Chapter 02)
     */
    showEyebrow?: boolean | null;
    /**
     * Show chapter main title on site
     */
    showTitle?: boolean | null;
    eyebrow: string;
    title: string;
    cards: {
      num: string;
      title: string;
      desc: string;
      dialogueTitle: string;
      userContent: string;
      aiContent: string;
      /**
       * Optional flip targets (legacy; not shown on current site)
       */
      flipCards?: string[] | null;
      id?: string | null;
    }[];
  };
  ctaSection?: {
    title: string;
    subtitle: string;
    primaryCta: string;
    secondaryCtas?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Show this campaign in the site header navigation
   */
  showInNav?: boolean | null;
  /**
   * Header link text (falls back to page title when empty)
   */
  navLabel?: string | null;
  /**
   * Lower numbers appear first in the header
   */
  navSort?: number | null;
  /**
   * Upload a .html file, or paste HTML below. When both are set, the file wins.
   */
  htmlFile?: (number | null) | Media;
  /**
   * Paste HTML here if you are not uploading a file
   */
  htmlBody?: string | null;
  /**
   * Open the header link in a new browser tab
   */
  openInNewTab?: boolean | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  localesPublished?: ('zh-Hans' | 'zh-Hant' | 'en' | 'ja' | 'ko')[] | null;
  seo?: {
    /**
     * Overrides page title for search engines when set
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  firstPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  site: number | Site;
  question: string;
  answer: string;
  sort: number;
  visible?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  firstPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  site: number | Site;
  /**
   * Stable id for home animation mapping (e.g. char-1). Not localized.
   */
  slug: string;
  /**
   * Gateway persona_key for chat (e.g. daozhang, tarot). Not localized.
   */
  personaKey?: string | null;
  name: string;
  /**
   * Subtitle shown under the name
   */
  title?: string | null;
  tagline: string;
  description: string;
  /**
   * Wisdom systems label (e.g. Tarot / Astrology)
   */
  system?: string | null;
  traits?: string[] | null;
  avatar?: (number | null) | Media;
  /**
   * Fallback static path when no media upload (e.g. /Character1_HalfBody.png)
   */
  avatarPath?: string | null;
  image?: (number | null) | Media;
  imagePath?: string | null;
  bgPath?: string | null;
  sort: number;
  visible?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  firstPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  site: number | Site;
  brandName: string;
  /**
   * Site-wide color theme for lingxia_home
   */
  themePreset: 'lingxia-gold' | 'lingxia-jade' | 'lingxia-festival';
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  pageLabels?: {
    blog?: {
      title?: string | null;
      description?: string | null;
    };
    faq?: {
      title?: string | null;
      description?: string | null;
    };
    characters?: {
      title?: string | null;
      description?: string | null;
    };
  };
  downloadLinks?: {
    appStore?: {
      label?: string | null;
      /**
       * Leave empty to use NEXT_PUBLIC_APP_STORE_URL from home .env
       */
      url?: string | null;
      /**
       * SVG/PNG recommended (~20px). Falls back to home /social/applelogo.svg
       */
      icon?: (number | null) | Media;
    };
    android?: {
      label?: string | null;
      /**
       * Leave empty to use NEXT_PUBLIC_ANDROID_URL from home .env
       */
      url?: string | null;
      /**
       * SVG/PNG recommended (~20px). Falls back to home /social/adrlogo.svg
       */
      icon?: (number | null) | Media;
    };
  };
  socialLinks?:
    | {
        platform: 'wechat' | 'weibo' | 'xiaohongshu' | 'douyin' | 'other';
        label: string;
        url: string;
        /**
         * Optional. Falls back to bundled icon in home /public/social/ by platform
         */
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  footerCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Plain text for noscript / GEO fallback on the home page
   */
  homeSeoParagraph?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  resource?: T;
  action?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  isSystem?: T;
  allSites?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  roles?: T;
  sites?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  primaryDomain?: T;
  defaultLocale?: T;
  enabledLocales?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  collection?: T;
  docId?: T;
  slug?: T;
  site?: T;
  at?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  site?: T;
  author?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  cover?: T;
  tags?: T;
  status?: T;
  publishedAt?: T;
  localesPublished?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  publishedBy?: T;
  firstPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  layout?: T;
  body?:
    | T
    | {
        richParagraph?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
      };
  heroSocial?:
    | T
    | {
        dividerText?: T;
      };
  chapterOne?:
    | T
    | {
        showEyebrow?: T;
        showTitle?: T;
        showPillarTitle?: T;
        showPillarBody?: T;
        eyebrow?: T;
        title?: T;
        pillars?:
          | T
          | {
              title?: T;
              body?: T;
              image?: T;
              id?: T;
            };
      };
  chapterTwo?:
    | T
    | {
        showEyebrow?: T;
        showTitle?: T;
        eyebrow?: T;
        title?: T;
        cards?:
          | T
          | {
              num?: T;
              title?: T;
              desc?: T;
              dialogueTitle?: T;
              userContent?: T;
              aiContent?: T;
              flipCards?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        primaryCta?: T;
        secondaryCtas?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  showInNav?: T;
  navLabel?: T;
  navSort?: T;
  htmlFile?: T;
  htmlBody?: T;
  openInNewTab?: T;
  status?: T;
  publishedAt?: T;
  localesPublished?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  publishedBy?: T;
  firstPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  site?: T;
  question?: T;
  answer?: T;
  sort?: T;
  visible?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedBy?: T;
  firstPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  site?: T;
  slug?: T;
  personaKey?: T;
  name?: T;
  title?: T;
  tagline?: T;
  description?: T;
  system?: T;
  traits?: T;
  avatar?: T;
  avatarPath?: T;
  image?: T;
  imagePath?: T;
  bgPath?: T;
  sort?: T;
  visible?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedBy?: T;
  firstPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  site?: T;
  brandName?: T;
  themePreset?: T;
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  pageLabels?:
    | T
    | {
        blog?:
          | T
          | {
              title?: T;
              description?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              description?: T;
            };
        characters?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  downloadLinks?:
    | T
    | {
        appStore?:
          | T
          | {
              label?: T;
              url?: T;
              icon?: T;
            };
        android?:
          | T
          | {
              label?: T;
              url?: T;
              icon?: T;
            };
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  footerCopy?: T;
  homeSeoParagraph?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}